# Format: "Actor ID": "Indexes of the <Property> you'd like a checkbox"
# Values Format: "Index #1, Index #2, ..." (i.e: <Property Index="1" .../>)
checkBox = {
    "ACTOR_OBJ_SWITCH": "1,2,3,4,5",
    "ACTOR_EN_FIREFLY": "1",
    "ACTOR_EN_DOOR": "1",
    "ACTOR_OBJ_TIMEBLOCK": "2,4"
}

# Used to draw the relevant props on Blender
# Format: "Actor ID": {Index: ["Type1,Type2,...", "Tag1,Tag2,...", "Index1,Index2,..."]}
tiedParams = {
    "ACTOR_EN_WALLMAS": {
        1: ["0002", "Flag", "1"],
    },
    "ACTOR_EN_HOLL": {
        1: ["00C0", "Flag", "1"],
    },
    "ACTOR_EN_RIVER_SOUND": {
        1: ["0000", "Property", "1"],
    },
    "ACTOR_EN_MB": {
        1: ["00FF", "Property", "1"],
    },
    "ACTOR_OBJ_SYOKUDAI": {
        1: ["1000", "Property", "1"],
    },
    "ACTOR_BG_MIZU_MOVEBG": {
        1: ["7000", "Property,Property,Property", "1,2,3"],
    },
    "ACTOR_EN_WOOD02": {
        1: ["0000,0001,0002,0003,0004,0005,0006,0007,0008,0009,000A", "Property", "3"],
    },
    "ACTOR_EN_TRAP": {
        1: ["0000", "Property,Property,Property,Property", "2,3,4,5"],
        2: ["0010,0020", "Property", "1"],
    },
    "ACTOR_DOOR_ANA": {
        1: [ "0000", "Property", "2"],
        2: [ "1000", "Property", "3"],
    },
    "ACTOR_BG_HAKA_MEGANEBG": {
        1: ["0003", "Flag", "1"],
    },
    "ACTOR_BG_MORI_HASHIRA4": {
        1: ["0001", "Flag", "1"],
    },
    "ACTOR_EN_WONDER_ITEM": {
        1: ["1800", "Property", "1"],
        2: ["1000", "Property", "2"],
    },
    "ACTOR_OBJ_SWITCH": {
        1: ["0000,0001", "Bool,Bool", "2,3"],
        2: ["0002", "Bool", "5"],
        3: ["0003,0004", "Bool", "4"],
    },
    "ACTOR_EN_HY": {
        1: ["0003,0007", "Property", "1"],
    },
    "ACTOR_BG_SPOT05_SOKO": {
        1: ["0001", "Property", "1"],
    },
    "ACTOR_BG_SPOT01_OBJECTS2": {
        1: ["0003", "Property", "1"],
    },
}

# Dictionnary containing every Actor IDs
actors = {
    "0000": "ACTOR_PLAYER",
    "0001": "ACTOR_UNSET_1",
    "0002": "ACTOR_EN_TEST",
    "0003": "ACTOR_UNSET_3",
    "0004": "ACTOR_EN_GIRLA",
    "0005": "ACTOR_UNSET_5",
    "0006": "ACTOR_UNSET_6",
    "0007": "ACTOR_EN_PART",
    "0008": "ACTOR_EN_LIGHT",
    "0009": "ACTOR_EN_DOOR",
    "000A": "ACTOR_EN_BOX",
    "000B": "ACTOR_BG_DY_YOSEIZO",
    "000C": "ACTOR_BG_HIDAN_FIREWALL",
    "000D": "ACTOR_EN_POH",
    "000E": "ACTOR_EN_OKUTA",
    "000F": "ACTOR_BG_YDAN_SP",
    "0010": "ACTOR_EN_BOM",
    "0011": "ACTOR_EN_WALLMAS",
    "0012": "ACTOR_EN_DODONGO",
    "0013": "ACTOR_EN_FIREFLY",
    "0014": "ACTOR_EN_HORSE",
    "0015": "ACTOR_EN_ITEM00",
    "0016": "ACTOR_EN_ARROW",
    "0017": "ACTOR_UNSET_17",
    "0018": "ACTOR_EN_ELF",
    "0019": "ACTOR_EN_NIW",
    "001A": "ACTOR_UNSET_1A",
    "001B": "ACTOR_EN_TITE",
    "001C": "ACTOR_EN_REEBA",
    "001D": "ACTOR_EN_PEEHAT",
    "001E": "ACTOR_EN_BUTTE",
    "001F": "ACTOR_UNSET_1F",
    "0020": "ACTOR_EN_INSECT",
    "0021": "ACTOR_EN_FISH",
    "0022": "ACTOR_UNSET_22",
    "0023": "ACTOR_EN_HOLL",
    "0024": "ACTOR_EN_SCENE_CHANGE",
    "0025": "ACTOR_EN_ZF",
    "0026": "ACTOR_EN_HATA",
    "0027": "ACTOR_BOSS_DODONGO",
    "0028": "ACTOR_BOSS_GOMA",
    "0029": "ACTOR_EN_ZL1",
    "002A": "ACTOR_EN_VIEWER",
    "002B": "ACTOR_EN_GOMA",
    "002C": "ACTOR_BG_PUSHBOX",
    "002D": "ACTOR_EN_BUBBLE",
    "002E": "ACTOR_DOOR_SHUTTER",
    "002F": "ACTOR_EN_DODOJR",
    "0030": "ACTOR_EN_BDFIRE",
    "0031": "ACTOR_UNSET_31",
    "0032": "ACTOR_EN_BOOM",
    "0033": "ACTOR_EN_TORCH2",
    "0034": "ACTOR_EN_BILI",
    "0035": "ACTOR_EN_TP",
    "0036": "ACTOR_UNSET_36",
    "0037": "ACTOR_EN_ST",
    "0038": "ACTOR_EN_BW",
    "0039": "ACTOR_EN_A_OBJ",
    "003A": "ACTOR_EN_EIYER",
    "003B": "ACTOR_EN_RIVER_SOUND",
    "003C": "ACTOR_EN_HORSE_NORMAL",
    "003D": "ACTOR_EN_OSSAN",
    "003E": "ACTOR_BG_TREEMOUTH",
    "003F": "ACTOR_BG_DODOAGO",
    "0040": "ACTOR_BG_HIDAN_DALM",
    "0041": "ACTOR_BG_HIDAN_HROCK",
    "0042": "ACTOR_EN_HORSE_GANON",
    "0043": "ACTOR_BG_HIDAN_ROCK",
    "0044": "ACTOR_BG_HIDAN_RSEKIZOU",
    "0045": "ACTOR_BG_HIDAN_SEKIZOU",
    "0046": "ACTOR_BG_HIDAN_SIMA",
    "0047": "ACTOR_BG_HIDAN_SYOKU",
    "0048": "ACTOR_EN_XC",
    "0049": "ACTOR_BG_HIDAN_CURTAIN",
    "004A": "ACTOR_BG_SPOT00_HANEBASI",
    "004B": "ACTOR_EN_MB",
    "004C": "ACTOR_EN_BOMBF",
    "004D": "ACTOR_EN_ZL2",
    "004E": "ACTOR_BG_HIDAN_FSLIFT",
    "004F": "ACTOR_EN_OE2",
    "0050": "ACTOR_BG_YDAN_HASI",
    "0051": "ACTOR_BG_YDAN_MARUTA",
    "0052": "ACTOR_BOSS_GANONDROF",
    "0053": "ACTOR_UNSET_53",
    "0054": "ACTOR_EN_AM",
    "0055": "ACTOR_EN_DEKUBABA",
    "0056": "ACTOR_EN_M_FIRE1",
    "0057": "ACTOR_EN_M_THUNDER",
    "0058": "ACTOR_BG_DDAN_JD",
    "0059": "ACTOR_BG_BREAKWALL",
    "005A": "ACTOR_EN_JJ",
    "005B": "ACTOR_EN_HORSE_ZELDA",
    "005C": "ACTOR_BG_DDAN_KD",
    "005D": "ACTOR_DOOR_WARP1",
    "005E": "ACTOR_OBJ_SYOKUDAI",
    "005F": "ACTOR_ITEM_B_HEART",
    "0060": "ACTOR_EN_DEKUNUTS",
    "0061": "ACTOR_BG_MENKURI_KAITEN",
    "0062": "ACTOR_BG_MENKURI_EYE",
    "0063": "ACTOR_EN_VALI",
    "0064": "ACTOR_BG_MIZU_MOVEBG",
    "0065": "ACTOR_BG_MIZU_WATER",
    "0066": "ACTOR_ARMS_HOOK",
    "0067": "ACTOR_EN_FHG",
    "0068": "ACTOR_BG_MORI_HINERI",
    "0069": "ACTOR_EN_BB",
    "006A": "ACTOR_BG_TOKI_HIKARI",
    "006B": "ACTOR_EN_YUKABYUN",
    "006C": "ACTOR_BG_TOKI_SWD",
    "006D": "ACTOR_EN_FHG_FIRE",
    "006E": "ACTOR_BG_MJIN",
    "006F": "ACTOR_BG_HIDAN_KOUSI",
    "0070": "ACTOR_DOOR_TOKI",
    "0071": "ACTOR_BG_HIDAN_HAMSTEP",
    "0072": "ACTOR_EN_BIRD",
    "0073": "ACTOR_UNSET_73",
    "0074": "ACTOR_UNSET_74",
    "0075": "ACTOR_UNSET_75",
    "0076": "ACTOR_UNSET_76",
    "0077": "ACTOR_EN_WOOD02",
    "0078": "ACTOR_UNSET_78",
    "0079": "ACTOR_UNSET_79",
    "007A": "ACTOR_UNSET_7A",
    "007B": "ACTOR_UNSET_7B",
    "007C": "ACTOR_EN_LIGHTBOX",
    "007D": "ACTOR_EN_PU_BOX",
    "007E": "ACTOR_UNSET_7E",
    "007F": "ACTOR_UNSET_7F",
    "0080": "ACTOR_EN_TRAP",
    "0081": "ACTOR_EN_AROW_TRAP",
    "0082": "ACTOR_EN_VASE",
    "0083": "ACTOR_UNSET_83",
    "0084": "ACTOR_EN_TA",
    "0085": "ACTOR_EN_TK",
    "0086": "ACTOR_BG_MORI_BIGST",
    "0087": "ACTOR_BG_MORI_ELEVATOR",
    "0088": "ACTOR_BG_MORI_KAITENKABE",
    "0089": "ACTOR_BG_MORI_RAKKATENJO",
    "008A": "ACTOR_EN_VM",
    "008B": "ACTOR_DEMO_EFFECT",
    "008C": "ACTOR_DEMO_KANKYO",
    "008D": "ACTOR_BG_HIDAN_FWBIG",
    "008E": "ACTOR_EN_FLOORMAS",
    "008F": "ACTOR_EN_HEISHI1",
    "0090": "ACTOR_EN_RD",
    "0091": "ACTOR_EN_PO_SISTERS",
    "0092": "ACTOR_BG_HEAVY_BLOCK",
    "0093": "ACTOR_BG_PO_EVENT",
    "0094": "ACTOR_OBJ_MURE",
    "0095": "ACTOR_EN_SW",
    "0096": "ACTOR_BOSS_FD",
    "0097": "ACTOR_OBJECT_KANKYO",
    "0098": "ACTOR_EN_DU",
    "0099": "ACTOR_EN_FD",
    "009A": "ACTOR_EN_HORSE_LINK_CHILD",
    "009B": "ACTOR_DOOR_ANA",
    "009C": "ACTOR_BG_SPOT02_OBJECTS",
    "009D": "ACTOR_BG_HAKA",
    "009E": "ACTOR_MAGIC_WIND",
    "009F": "ACTOR_MAGIC_FIRE",
    "00A0": "ACTOR_UNSET_A0",
    "00A1": "ACTOR_EN_RU1",
    "00A2": "ACTOR_BOSS_FD2",
    "00A3": "ACTOR_EN_FD_FIRE",
    "00A4": "ACTOR_EN_DH",
    "00A5": "ACTOR_EN_DHA",
    "00A6": "ACTOR_EN_RL",
    "00A7": "ACTOR_EN_ENCOUNT1",
    "00A8": "ACTOR_DEMO_DU",
    "00A9": "ACTOR_DEMO_IM",
    "00AA": "ACTOR_DEMO_TRE_LGT",
    "00AB": "ACTOR_EN_FW",
    "00AC": "ACTOR_BG_VB_SIMA",
    "00AD": "ACTOR_EN_VB_BALL",
    "00AE": "ACTOR_BG_HAKA_MEGANE",
    "00AF": "ACTOR_BG_HAKA_MEGANEBG",
    "00B0": "ACTOR_BG_HAKA_SHIP",
    "00B1": "ACTOR_BG_HAKA_SGAMI",
    "00B2": "ACTOR_UNSET_B2",
    "00B3": "ACTOR_EN_HEISHI2",
    "00B4": "ACTOR_EN_ENCOUNT2",
    "00B5": "ACTOR_EN_FIRE_ROCK",
    "00B6": "ACTOR_EN_BROB",
    "00B7": "ACTOR_MIR_RAY",
    "00B8": "ACTOR_BG_SPOT09_OBJ",
    "00B9": "ACTOR_BG_SPOT18_OBJ",
    "00BA": "ACTOR_BOSS_VA",
    "00BB": "ACTOR_BG_HAKA_TUBO",
    "00BC": "ACTOR_BG_HAKA_TRAP",
    "00BD": "ACTOR_BG_HAKA_HUTA",
    "00BE": "ACTOR_BG_HAKA_ZOU",
    "00BF": "ACTOR_BG_SPOT17_FUNEN",
    "00C0": "ACTOR_EN_SYATEKI_ITM",
    "00C1": "ACTOR_EN_SYATEKI_MAN",
    "00C2": "ACTOR_EN_TANA",
    "00C3": "ACTOR_EN_NB",
    "00C4": "ACTOR_BOSS_MO",
    "00C5": "ACTOR_EN_SB",
    "00C6": "ACTOR_EN_BIGOKUTA",
    "00C7": "ACTOR_EN_KAREBABA",
    "00C8": "ACTOR_BG_BDAN_OBJECTS",
    "00C9": "ACTOR_DEMO_SA",
    "00CA": "ACTOR_DEMO_GO",
    "00CB": "ACTOR_EN_IN",
    "00CC": "ACTOR_EN_TR",
    "00CD": "ACTOR_BG_SPOT16_BOMBSTONE",
    "00CE": "ACTOR_UNSET_CE",
    "00CF": "ACTOR_BG_HIDAN_KOWARERUKABE",
    "00D0": "ACTOR_BG_BOMBWALL",
    "00D1": "ACTOR_BG_SPOT08_ICEBLOCK",
    "00D2": "ACTOR_EN_RU2",
    "00D3": "ACTOR_OBJ_DEKUJR",
    "00D4": "ACTOR_BG_MIZU_UZU",
    "00D5": "ACTOR_BG_SPOT06_OBJECTS",
    "00D6": "ACTOR_BG_ICE_OBJECTS",
    "00D7": "ACTOR_BG_HAKA_WATER",
    "00D8": "ACTOR_UNSET_D8",
    "00D9": "ACTOR_EN_MA2",
    "00DA": "ACTOR_EN_BOM_CHU",
    "00DB": "ACTOR_EN_HORSE_GAME_CHECK",
    "00DC": "ACTOR_BOSS_TW",
    "00DD": "ACTOR_EN_RR",
    "00DE": "ACTOR_EN_BA",
    "00DF": "ACTOR_EN_BX",
    "00E0": "ACTOR_EN_ANUBICE",
    "00E1": "ACTOR_EN_ANUBICE_FIRE",
    "00E2": "ACTOR_BG_MORI_HASHIGO",
    "00E3": "ACTOR_BG_MORI_HASHIRA4",
    "00E4": "ACTOR_BG_MORI_IDOMIZU",
    "00E5": "ACTOR_BG_SPOT16_DOUGHNUT",
    "00E6": "ACTOR_BG_BDAN_SWITCH",
    "00E7": "ACTOR_EN_MA1",
    "00E8": "ACTOR_BOSS_GANON",
    "00E9": "ACTOR_BOSS_SST",
    "00EA": "ACTOR_UNSET_EA",
    "00EB": "ACTOR_UNSET_EB",
    "00EC": "ACTOR_EN_NY",
    "00ED": "ACTOR_EN_FR",
    "00EE": "ACTOR_ITEM_SHIELD",
    "00EF": "ACTOR_BG_ICE_SHELTER",
    "00F0": "ACTOR_EN_ICE_HONO",
    "00F1": "ACTOR_ITEM_OCARINA",
    "00F2": "ACTOR_UNSET_F2",
    "00F3": "ACTOR_UNSET_F3",
    "00F4": "ACTOR_MAGIC_DARK",
    "00F5": "ACTOR_DEMO_6K",
    "00F6": "ACTOR_EN_ANUBICE_TAG",
    "00F7": "ACTOR_BG_HAKA_GATE",
    "00F8": "ACTOR_BG_SPOT15_SAKU",
    "00F9": "ACTOR_BG_JYA_GOROIWA",
    "00FA": "ACTOR_BG_JYA_ZURERUKABE",
    "00FB": "ACTOR_UNSET_FB",
    "00FC": "ACTOR_BG_JYA_COBRA",
    "00FD": "ACTOR_BG_JYA_KANAAMI",
    "00FE": "ACTOR_FISHING",
    "00FF": "ACTOR_OBJ_OSHIHIKI",
    "0100": "ACTOR_BG_GATE_SHUTTER",
    "0101": "ACTOR_EFF_DUST",
    "0102": "ACTOR_BG_SPOT01_FUSYA",
    "0103": "ACTOR_BG_SPOT01_IDOHASHIRA",
    "0104": "ACTOR_BG_SPOT01_IDOMIZU",
    "0105": "ACTOR_BG_PO_SYOKUDAI",
    "0106": "ACTOR_BG_GANON_OTYUKA",
    "0107": "ACTOR_BG_SPOT15_RRBOX",
    "0108": "ACTOR_BG_UMAJUMP",
    "0109": "ACTOR_UNSET_109",
    "010A": "ACTOR_ARROW_FIRE",
    "010B": "ACTOR_ARROW_ICE",
    "010C": "ACTOR_ARROW_LIGHT",
    "010D": "ACTOR_UNSET_10D",
    "010E": "ACTOR_UNSET_10E",
    "010F": "ACTOR_ITEM_ETCETERA",
    "0110": "ACTOR_OBJ_KIBAKO",
    "0111": "ACTOR_OBJ_TSUBO",
    "0112": "ACTOR_EN_WONDER_ITEM",
    "0113": "ACTOR_EN_IK",
    "0114": "ACTOR_DEMO_IK",
    "0115": "ACTOR_EN_SKJ",
    "0116": "ACTOR_EN_SKJNEEDLE",
    "0117": "ACTOR_EN_G_SWITCH",
    "0118": "ACTOR_DEMO_EXT",
    "0119": "ACTOR_DEMO_SHD",
    "011A": "ACTOR_EN_DNS",
    "011B": "ACTOR_ELF_MSG",
    "011C": "ACTOR_EN_HONOTRAP",
    "011D": "ACTOR_EN_TUBO_TRAP",
    "011E": "ACTOR_OBJ_ICE_POLY",
    "011F": "ACTOR_BG_SPOT03_TAKI",
    "0120": "ACTOR_BG_SPOT07_TAKI",
    "0121": "ACTOR_EN_FZ",
    "0122": "ACTOR_EN_PO_RELAY",
    "0123": "ACTOR_BG_RELAY_OBJECTS",
    "0124": "ACTOR_EN_DIVING_GAME",
    "0125": "ACTOR_EN_KUSA",
    "0126": "ACTOR_OBJ_BEAN",
    "0127": "ACTOR_OBJ_BOMBIWA",
    "0128": "ACTOR_UNSET_128",
    "0129": "ACTOR_UNSET_129",
    "012A": "ACTOR_OBJ_SWITCH",
    "012B": "ACTOR_OBJ_ELEVATOR",
    "012C": "ACTOR_OBJ_LIFT",
    "012D": "ACTOR_OBJ_HSBLOCK",
    "012E": "ACTOR_EN_OKARINA_TAG",
    "012F": "ACTOR_EN_YABUSAME_MARK",
    "0130": "ACTOR_EN_GOROIWA",
    "0131": "ACTOR_EN_EX_RUPPY",
    "0132": "ACTOR_EN_TORYO",
    "0133": "ACTOR_EN_DAIKU",
    "0134": "ACTOR_UNSET_134",
    "0135": "ACTOR_EN_NWC",
    "0136": "ACTOR_EN_BLKOBJ",
    "0137": "ACTOR_ITEM_INBOX",
    "0138": "ACTOR_EN_GE1",
    "0139": "ACTOR_OBJ_BLOCKSTOP",
    "013A": "ACTOR_EN_SDA",
    "013B": "ACTOR_EN_CLEAR_TAG",
    "013C": "ACTOR_EN_NIW_LADY",
    "013D": "ACTOR_EN_GM",
    "013E": "ACTOR_EN_MS",
    "013F": "ACTOR_EN_HS",
    "0140": "ACTOR_BG_INGATE",
    "0141": "ACTOR_EN_KANBAN",
    "0142": "ACTOR_EN_HEISHI3",
    "0143": "ACTOR_EN_SYATEKI_NIW",
    "0144": "ACTOR_EN_ATTACK_NIW",
    "0145": "ACTOR_BG_SPOT01_IDOSOKO",
    "0146": "ACTOR_EN_SA",
    "0147": "ACTOR_EN_WONDER_TALK",
    "0148": "ACTOR_BG_GJYO_BRIDGE",
    "0149": "ACTOR_EN_DS",
    "014A": "ACTOR_EN_MK",
    "014B": "ACTOR_EN_BOM_BOWL_MAN",
    "014C": "ACTOR_EN_BOM_BOWL_PIT",
    "014D": "ACTOR_EN_OWL",
    "014E": "ACTOR_EN_ISHI",
    "014F": "ACTOR_OBJ_HANA",
    "0150": "ACTOR_OBJ_LIGHTSWITCH",
    "0151": "ACTOR_OBJ_MURE2",
    "0152": "ACTOR_EN_GO",
    "0153": "ACTOR_EN_FU",
    "0154": "ACTOR_UNSET_154",
    "0155": "ACTOR_EN_CHANGER",
    "0156": "ACTOR_BG_JYA_MEGAMI",
    "0157": "ACTOR_BG_JYA_LIFT",
    "0158": "ACTOR_BG_JYA_BIGMIRROR",
    "0159": "ACTOR_BG_JYA_BOMBCHUIWA",
    "015A": "ACTOR_BG_JYA_AMISHUTTER",
    "015B": "ACTOR_BG_JYA_BOMBIWA",
    "015C": "ACTOR_BG_SPOT18_BASKET",
    "015D": "ACTOR_UNSET_15D",
    "015E": "ACTOR_EN_GANON_ORGAN",
    "015F": "ACTOR_EN_SIOFUKI",
    "0160": "ACTOR_EN_STREAM",
    "0161": "ACTOR_UNSET_161",
    "0162": "ACTOR_EN_MM",
    "0163": "ACTOR_EN_KO",
    "0164": "ACTOR_EN_KZ",
    "0165": "ACTOR_EN_WEATHER_TAG",
    "0166": "ACTOR_BG_SST_FLOOR",
    "0167": "ACTOR_EN_ANI",
    "0168": "ACTOR_EN_EX_ITEM",
    "0169": "ACTOR_BG_JYA_IRONOBJ",
    "016A": "ACTOR_EN_JS",
    "016B": "ACTOR_EN_JSJUTAN",
    "016C": "ACTOR_EN_CS",
    "016D": "ACTOR_EN_MD",
    "016E": "ACTOR_EN_HY",
    "016F": "ACTOR_EN_GANON_MANT",
    "0170": "ACTOR_EN_OKARINA_EFFECT",
    "0171": "ACTOR_EN_MAG",
    "0172": "ACTOR_DOOR_GERUDO",
    "0173": "ACTOR_ELF_MSG2",
    "0174": "ACTOR_DEMO_GT",
    "0175": "ACTOR_EN_PO_FIELD",
    "0176": "ACTOR_EFC_ERUPC",
    "0177": "ACTOR_BG_ZG",
    "0178": "ACTOR_EN_HEISHI4",
    "0179": "ACTOR_EN_ZL3",
    "017A": "ACTOR_BOSS_GANON2",
    "017B": "ACTOR_EN_KAKASI",
    "017C": "ACTOR_EN_TAKARA_MAN",
    "017D": "ACTOR_OBJ_MAKEOSHIHIKI",
    "017E": "ACTOR_OCEFF_SPOT",
    "017F": "ACTOR_END_TITLE",
    "0180": "ACTOR_UNSET_180",
    "0181": "ACTOR_EN_TORCH",
    "0182": "ACTOR_DEMO_EC",
    "0183": "ACTOR_SHOT_SUN",
    "0184": "ACTOR_EN_DY_EXTRA",
    "0185": "ACTOR_EN_WONDER_TALK2",
    "0186": "ACTOR_EN_GE2",
    "0187": "ACTOR_OBJ_ROOMTIMER",
    "0188": "ACTOR_EN_SSH",
    "0189": "ACTOR_EN_STH",
    "018A": "ACTOR_OCEFF_WIPE",
    "018B": "ACTOR_OCEFF_STORM",
    "018C": "ACTOR_EN_WEIYER",
    "018D": "ACTOR_BG_SPOT05_SOKO",
    "018E": "ACTOR_BG_JYA_1FLIFT",
    "018F": "ACTOR_BG_JYA_HAHENIRON",
    "0190": "ACTOR_BG_SPOT12_GATE",
    "0191": "ACTOR_BG_SPOT12_SAKU",
    "0192": "ACTOR_EN_HINTNUTS",
    "0193": "ACTOR_EN_NUTSBALL",
    "0194": "ACTOR_BG_SPOT00_BREAK",
    "0195": "ACTOR_EN_SHOPNUTS",
    "0196": "ACTOR_EN_IT",
    "0197": "ACTOR_EN_GELDB",
    "0198": "ACTOR_OCEFF_WIPE2",
    "0199": "ACTOR_OCEFF_WIPE3",
    "019A": "ACTOR_EN_NIW_GIRL",
    "019B": "ACTOR_EN_DOG",
    "019C": "ACTOR_EN_SI",
    "019D": "ACTOR_BG_SPOT01_OBJECTS2",
    "019E": "ACTOR_OBJ_COMB",
    "019F": "ACTOR_BG_SPOT11_BAKUDANKABE",
    "01A0": "ACTOR_OBJ_KIBAKO2",
    "01A1": "ACTOR_EN_DNT_DEMO",
    "01A2": "ACTOR_EN_DNT_JIJI",
    "01A3": "ACTOR_EN_DNT_NOMAL",
    "01A4": "ACTOR_EN_GUEST",
    "01A5": "ACTOR_BG_BOM_GUARD",
    "01A6": "ACTOR_EN_HS2",
    "01A7": "ACTOR_DEMO_KEKKAI",
    "01A8": "ACTOR_BG_SPOT08_BAKUDANKABE",
    "01A9": "ACTOR_BG_SPOT17_BAKUDANKABE",
    "01AA": "ACTOR_UNSET_1AA",
    "01AB": "ACTOR_OBJ_MURE3",
    "01AC": "ACTOR_EN_TG",
    "01AD": "ACTOR_EN_MU",
    "01AE": "ACTOR_EN_GO2",
    "01AF": "ACTOR_EN_WF",
    "01B0": "ACTOR_EN_SKB",
    "01B1": "ACTOR_DEMO_GJ",
    "01B2": "ACTOR_DEMO_GEFF",
    "01B3": "ACTOR_BG_GND_FIREMEIRO",
    "01B4": "ACTOR_BG_GND_DARKMEIRO",
    "01B5": "ACTOR_BG_GND_SOULMEIRO",
    "01B6": "ACTOR_BG_GND_NISEKABE",
    "01B7": "ACTOR_BG_GND_ICEBLOCK",
    "01B8": "ACTOR_EN_GB",
    "01B9": "ACTOR_EN_GS",
    "01BA": "ACTOR_BG_MIZU_BWALL",
    "01BB": "ACTOR_BG_MIZU_SHUTTER",
    "01BC": "ACTOR_EN_DAIKU_KAKARIKO",
    "01BD": "ACTOR_BG_BOWL_WALL",
    "01BE": "ACTOR_EN_WALL_TUBO",
    "01BF": "ACTOR_EN_PO_DESERT",
    "01C0": "ACTOR_EN_CROW",
    "01C1": "ACTOR_DOOR_KILLER",
    "01C2": "ACTOR_BG_SPOT11_OASIS",
    "01C3": "ACTOR_BG_SPOT18_FUTA",
    "01C4": "ACTOR_BG_SPOT18_SHUTTER",
    "01C5": "ACTOR_EN_MA3",
    "01C6": "ACTOR_EN_COW",
    "01C7": "ACTOR_BG_ICE_TURARA",
    "01C8": "ACTOR_BG_ICE_SHUTTER",
    "01C9": "ACTOR_EN_KAKASI2",
    "01CA": "ACTOR_EN_KAKASI3",
    "01CB": "ACTOR_OCEFF_WIPE4",
    "01CC": "ACTOR_EN_EG",
    "01CD": "ACTOR_BG_MENKURI_NISEKABE",
    "01CE": "ACTOR_EN_ZO",
    "01CF": "ACTOR_OBJ_MAKEKINSUTA",
    "01D0": "ACTOR_EN_GE3",
    "01D1": "ACTOR_OBJ_TIMEBLOCK",
    "01D2": "ACTOR_OBJ_HAMISHI",
    "01D3": "ACTOR_EN_ZL4",
    "01D4": "ACTOR_EN_MM2",
    "01D5": "ACTOR_BG_JYA_BLOCK",
    "01D6": "ACTOR_OBJ_WARP2BLOCK"
}

# Dictionnary containing every Object IDs
objects = {
    "0000": "OBJECT_UNSET_0",
    "0001": "OBJECT_GAMEPLAY_KEEP",
    "0002": "OBJECT_GAMEPLAY_FIELD_KEEP",
    "0003": "OBJECT_GAMEPLAY_DANGEON_KEEP",
    "0004": "OBJECT_UNSET_4",
    "0005": "OBJECT_UNSET_5",
    "0006": "OBJECT_HUMAN",
    "0007": "OBJECT_OKUTA",
    "0008": "OBJECT_CROW",
    "0009": "OBJECT_POH",
    "000A": "OBJECT_DY_OBJ",
    "000B": "OBJECT_WALLMASTER",
    "000C": "OBJECT_DODONGO",
    "000D": "OBJECT_FIREFLY",
    "000E": "OBJECT_BOX",
    "000F": "OBJECT_FIRE",
    "0010": "OBJECT_UNSET_10",
    "0011": "OBJECT_UNSET_11",
    "0012": "OBJECT_BUBBLE",
    "0013": "OBJECT_NIW",
    "0014": "OBJECT_LINK_BOY",
    "0015": "OBJECT_LINK_CHILD",
    "0016": "OBJECT_TITE",
    "0017": "OBJECT_REEBA",
    "0018": "OBJECT_PEEHAT",
    "0019": "OBJECT_KINGDODONGO",
    "001A": "OBJECT_HORSE",
    "001B": "OBJECT_ZF",
    "001C": "OBJECT_GOMA",
    "001D": "OBJECT_ZL1",
    "001E": "OBJECT_GOL",
    "001F": "OBJECT_DODOJR",
    "0020": "OBJECT_TORCH2",
    "0021": "OBJECT_BL",
    "0022": "OBJECT_TP",
    "0023": "OBJECT_OA1",
    "0024": "OBJECT_ST",
    "0025": "OBJECT_BW",
    "0026": "OBJECT_EI",
    "0027": "OBJECT_HORSE_NORMAL",
    "0028": "OBJECT_OB1",
    "0029": "OBJECT_O_ANIME",
    "002A": "OBJECT_SPOT04_OBJECTS",
    "002B": "OBJECT_DDAN_OBJECTS",
    "002C": "OBJECT_HIDAN_OBJECTS",
    "002D": "OBJECT_HORSE_GANON",
    "002E": "OBJECT_OA2",
    "002F": "OBJECT_SPOT00_OBJECTS",
    "0030": "OBJECT_MB",
    "0031": "OBJECT_BOMBF",
    "0032": "OBJECT_SK2",
    "0033": "OBJECT_OE1",
    "0034": "OBJECT_OE_ANIME",
    "0035": "OBJECT_OE2",
    "0036": "OBJECT_YDAN_OBJECTS",
    "0037": "OBJECT_GND",
    "0038": "OBJECT_AM",
    "0039": "OBJECT_DEKUBABA",
    "003A": "OBJECT_UNSET_3A",
    "003B": "OBJECT_OA3",
    "003C": "OBJECT_OA4",
    "003D": "OBJECT_OA5",
    "003E": "OBJECT_OA6",
    "003F": "OBJECT_OA7",
    "0040": "OBJECT_JJ",
    "0041": "OBJECT_OA8",
    "0042": "OBJECT_OA9",
    "0043": "OBJECT_OB2",
    "0044": "OBJECT_OB3",
    "0045": "OBJECT_OB4",
    "0046": "OBJECT_HORSE_ZELDA",
    "0047": "OBJECT_OPENING_DEMO1",
    "0048": "OBJECT_WARP1",
    "0049": "OBJECT_B_HEART",
    "004A": "OBJECT_DEKUNUTS",
    "004B": "OBJECT_OE3",
    "004C": "OBJECT_OE4",
    "004D": "OBJECT_MENKURI_OBJECTS",
    "004E": "OBJECT_OE5",
    "004F": "OBJECT_OE6",
    "0050": "OBJECT_OE7",
    "0051": "OBJECT_OE8",
    "0052": "OBJECT_OE9",
    "0053": "OBJECT_OE10",
    "0054": "OBJECT_OE11",
    "0055": "OBJECT_OE12",
    "0056": "OBJECT_VALI",
    "0057": "OBJECT_OA10",
    "0058": "OBJECT_OA11",
    "0059": "OBJECT_MIZU_OBJECTS",
    "005A": "OBJECT_FHG",
    "005B": "OBJECT_OSSAN",
    "005C": "OBJECT_MORI_HINERI1",
    "005D": "OBJECT_BB",
    "005E": "OBJECT_TOKI_OBJECTS",
    "005F": "OBJECT_YUKABYUN",
    "0060": "OBJECT_ZL2",
    "0061": "OBJECT_MJIN",
    "0062": "OBJECT_MJIN_FLASH",
    "0063": "OBJECT_MJIN_DARK",
    "0064": "OBJECT_MJIN_FLAME",
    "0065": "OBJECT_MJIN_ICE",
    "0066": "OBJECT_MJIN_SOUL",
    "0067": "OBJECT_MJIN_WIND",
    "0068": "OBJECT_MJIN_OKA",
    "0069": "OBJECT_HAKA_OBJECTS",
    "006A": "OBJECT_SPOT06_OBJECTS",
    "006B": "OBJECT_ICE_OBJECTS",
    "006C": "OBJECT_RELAY_OBJECTS",
    "006D": "OBJECT_PO_FIELD",
    "006E": "OBJECT_PO_COMPOSER",
    "006F": "OBJECT_MORI_HINERI1A",
    "0070": "OBJECT_MORI_HINERI2",
    "0071": "OBJECT_MORI_HINERI2A",
    "0072": "OBJECT_MORI_OBJECTS",
    "0073": "OBJECT_MORI_TEX",
    "0074": "OBJECT_SPOT08_OBJ",
    "0075": "OBJECT_WARP2",
    "0076": "OBJECT_HATA",
    "0077": "OBJECT_BIRD",
    "0078": "OBJECT_UNSET_78",
    "0079": "OBJECT_UNSET_79",
    "007A": "OBJECT_UNSET_7A",
    "007B": "OBJECT_UNSET_7B",
    "007C": "OBJECT_WOOD02",
    "007D": "OBJECT_UNSET_7D",
    "007E": "OBJECT_UNSET_7E",
    "007F": "OBJECT_UNSET_7F",
    "0080": "OBJECT_UNSET_80",
    "0081": "OBJECT_LIGHTBOX",
    "0082": "OBJECT_PU_BOX",
    "0083": "OBJECT_UNSET_83",
    "0084": "OBJECT_UNSET_84",
    "0085": "OBJECT_TRAP",
    "0086": "OBJECT_VASE",
    "0087": "OBJECT_IM",
    "0088": "OBJECT_TA",
    "0089": "OBJECT_TK",
    "008A": "OBJECT_XC",
    "008B": "OBJECT_VM",
    "008C": "OBJECT_BV",
    "008D": "OBJECT_HAKACH_OBJECTS",
    "008E": "OBJECT_EFC_CRYSTAL_LIGHT",
    "008F": "OBJECT_EFC_FIRE_BALL",
    "0090": "OBJECT_EFC_FLASH",
    "0091": "OBJECT_EFC_LGT_SHOWER",
    "0092": "OBJECT_EFC_STAR_FIELD",
    "0093": "OBJECT_GOD_LGT",
    "0094": "OBJECT_LIGHT_RING",
    "0095": "OBJECT_TRIFORCE_SPOT",
    "0096": "OBJECT_BDAN_OBJECTS",
    "0097": "OBJECT_SD",
    "0098": "OBJECT_RD",
    "0099": "OBJECT_PO_SISTERS",
    "009A": "OBJECT_HEAVY_OBJECT",
    "009B": "OBJECT_GNDD",
    "009C": "OBJECT_FD",
    "009D": "OBJECT_DU",
    "009E": "OBJECT_FW",
    "009F": "OBJECT_MEDAL",
    "00A0": "OBJECT_HORSE_LINK_CHILD",
    "00A1": "OBJECT_SPOT02_OBJECTS",
    "00A2": "OBJECT_HAKA",
    "00A3": "OBJECT_RU1",
    "00A4": "OBJECT_SYOKUDAI",
    "00A5": "OBJECT_FD2",
    "00A6": "OBJECT_DH",
    "00A7": "OBJECT_RL",
    "00A8": "OBJECT_EFC_TW",
    "00A9": "OBJECT_DEMO_TRE_LGT",
    "00AA": "OBJECT_GI_KEY",
    "00AB": "OBJECT_MIR_RAY",
    "00AC": "OBJECT_BROB",
    "00AD": "OBJECT_GI_JEWEL",
    "00AE": "OBJECT_SPOT09_OBJ",
    "00AF": "OBJECT_SPOT18_OBJ",
    "00B0": "OBJECT_BDOOR",
    "00B1": "OBJECT_SPOT17_OBJ",
    "00B2": "OBJECT_SHOP_DUNGEN",
    "00B3": "OBJECT_NB",
    "00B4": "OBJECT_MO",
    "00B5": "OBJECT_SB",
    "00B6": "OBJECT_GI_MELODY",
    "00B7": "OBJECT_GI_HEART",
    "00B8": "OBJECT_GI_COMPASS",
    "00B9": "OBJECT_GI_BOSSKEY",
    "00BA": "OBJECT_GI_MEDAL",
    "00BB": "OBJECT_GI_NUTS",
    "00BC": "OBJECT_SA",
    "00BD": "OBJECT_GI_HEARTS",
    "00BE": "OBJECT_GI_ARROWCASE",
    "00BF": "OBJECT_GI_BOMBPOUCH",
    "00C0": "OBJECT_IN",
    "00C1": "OBJECT_TR",
    "00C2": "OBJECT_SPOT16_OBJ",
    "00C3": "OBJECT_OE1S",
    "00C4": "OBJECT_OE4S",
    "00C5": "OBJECT_OS_ANIME",
    "00C6": "OBJECT_GI_BOTTLE",
    "00C7": "OBJECT_GI_STICK",
    "00C8": "OBJECT_GI_MAP",
    "00C9": "OBJECT_OF1D_MAP",
    "00CA": "OBJECT_RU2",
    "00CB": "OBJECT_GI_SHIELD_1",
    "00CC": "OBJECT_DEKUJR",
    "00CD": "OBJECT_GI_MAGICPOT",
    "00CE": "OBJECT_GI_BOMB_1",
    "00CF": "OBJECT_OF1S",
    "00D0": "OBJECT_MA2",
    "00D1": "OBJECT_GI_PURSE",
    "00D2": "OBJECT_HNI",
    "00D3": "OBJECT_TW",
    "00D4": "OBJECT_RR",
    "00D5": "OBJECT_BXA",
    "00D6": "OBJECT_ANUBICE",
    "00D7": "OBJECT_GI_GERUDO",
    "00D8": "OBJECT_GI_ARROW",
    "00D9": "OBJECT_GI_BOMB_2",
    "00DA": "OBJECT_GI_EGG",
    "00DB": "OBJECT_GI_SCALE",
    "00DC": "OBJECT_GI_SHIELD_2",
    "00DD": "OBJECT_GI_HOOKSHOT",
    "00DE": "OBJECT_GI_OCARINA",
    "00DF": "OBJECT_GI_MILK",
    "00E0": "OBJECT_MA1",
    "00E1": "OBJECT_GANON",
    "00E2": "OBJECT_SST",
    "00E3": "OBJECT_NY_UNUSED",
    "00E4": "OBJECT_UNSET_E4",
    "00E5": "OBJECT_NY",
    "00E6": "OBJECT_FR",
    "00E7": "OBJECT_GI_PACHINKO",
    "00E8": "OBJECT_GI_BOOMERANG",
    "00E9": "OBJECT_GI_BOW",
    "00EA": "OBJECT_GI_GLASSES",
    "00EB": "OBJECT_GI_LIQUID",
    "00EC": "OBJECT_ANI",
    "00ED": "OBJECT_DEMO_6K",
    "00EE": "OBJECT_GI_SHIELD_3",
    "00EF": "OBJECT_GI_LETTER",
    "00F0": "OBJECT_SPOT15_OBJ",
    "00F1": "OBJECT_JYA_OBJ",
    "00F2": "OBJECT_GI_CLOTHES",
    "00F3": "OBJECT_GI_BEAN",
    "00F4": "OBJECT_GI_FISH",
    "00F5": "OBJECT_GI_SAW",
    "00F6": "OBJECT_GI_HAMMER",
    "00F7": "OBJECT_GI_GRASS",
    "00F8": "OBJECT_GI_LONGSWORD",
    "00F9": "OBJECT_SPOT01_OBJECTS",
    "00FA": "OBJECT_MD_UNUSED",
    "00FB": "OBJECT_MD",
    "00FC": "OBJECT_KM1",
    "00FD": "OBJECT_KW1",
    "00FE": "OBJECT_ZO",
    "00FF": "OBJECT_KZ",
    "0100": "OBJECT_UMAJUMP",
    "0101": "OBJECT_MASTERKOKIRI",
    "0102": "OBJECT_MASTERKOKIRIHEAD",
    "0103": "OBJECT_MASTERGOLON",
    "0104": "OBJECT_MASTERZOORA",
    "0105": "OBJECT_AOB",
    "0106": "OBJECT_IK",
    "0107": "OBJECT_AHG",
    "0108": "OBJECT_CNE",
    "0109": "OBJECT_GI_NIWATORI",
    "010A": "OBJECT_SKJ",
    "010B": "OBJECT_GI_BOTTLE_LETTER",
    "010C": "OBJECT_BJI",
    "010D": "OBJECT_BBA",
    "010E": "OBJECT_GI_OCARINA_0",
    "010F": "OBJECT_DS",
    "0110": "OBJECT_ANE",
    "0111": "OBJECT_BOJ",
    "0112": "OBJECT_SPOT03_OBJECT",
    "0113": "OBJECT_SPOT07_OBJECT",
    "0114": "OBJECT_FZ",
    "0115": "OBJECT_BOB",
    "0116": "OBJECT_GE1",
    "0117": "OBJECT_YABUSAME_POINT",
    "0118": "OBJECT_GI_BOOTS_2",
    "0119": "OBJECT_GI_SEED",
    "011A": "OBJECT_GND_MAGIC",
    "011B": "OBJECT_D_ELEVATOR",
    "011C": "OBJECT_D_HSBLOCK",
    "011D": "OBJECT_D_LIFT",
    "011E": "OBJECT_MAMENOKI",
    "011F": "OBJECT_GOROIWA",
    "0120": "OBJECT_UNSET_120",
    "0121": "OBJECT_TORYO",
    "0122": "OBJECT_DAIKU",
    "0123": "OBJECT_UNSET_123",
    "0124": "OBJECT_NWC",
    "0125": "OBJECT_BLKOBJ",
    "0126": "OBJECT_GM",
    "0127": "OBJECT_MS",
    "0128": "OBJECT_HS",
    "0129": "OBJECT_INGATE",
    "012A": "OBJECT_LIGHTSWITCH",
    "012B": "OBJECT_KUSA",
    "012C": "OBJECT_TSUBO",
    "012D": "OBJECT_GI_GLOVES",
    "012E": "OBJECT_GI_COIN",
    "012F": "OBJECT_KANBAN",
    "0130": "OBJECT_GJYO_OBJECTS",
    "0131": "OBJECT_OWL",
    "0132": "OBJECT_MK",
    "0133": "OBJECT_FU",
    "0134": "OBJECT_GI_KI_TAN_MASK",
    "0135": "OBJECT_GI_REDEAD_MASK",
    "0136": "OBJECT_GI_SKJ_MASK",
    "0137": "OBJECT_GI_RABIT_MASK",
    "0138": "OBJECT_GI_TRUTH_MASK",
    "0139": "OBJECT_GANON_OBJECTS",
    "013A": "OBJECT_SIOFUKI",
    "013B": "OBJECT_STREAM",
    "013C": "OBJECT_MM",
    "013D": "OBJECT_FA",
    "013E": "OBJECT_OS",
    "013F": "OBJECT_GI_EYE_LOTION",
    "0140": "OBJECT_GI_POWDER",
    "0141": "OBJECT_GI_MUSHROOM",
    "0142": "OBJECT_GI_TICKETSTONE",
    "0143": "OBJECT_GI_BROKENSWORD",
    "0144": "OBJECT_JS",
    "0145": "OBJECT_CS",
    "0146": "OBJECT_GI_PRESCRIPTION",
    "0147": "OBJECT_GI_BRACELET",
    "0148": "OBJECT_GI_SOLDOUT",
    "0149": "OBJECT_GI_FROG",
    "014A": "OBJECT_MAG",
    "014B": "OBJECT_DOOR_GERUDO",
    "014C": "OBJECT_GT",
    "014D": "OBJECT_EFC_ERUPC",
    "014E": "OBJECT_ZL2_ANIME1",
    "014F": "OBJECT_ZL2_ANIME2",
    "0150": "OBJECT_GI_GOLONMASK",
    "0151": "OBJECT_GI_ZORAMASK",
    "0152": "OBJECT_GI_GERUDOMASK",
    "0153": "OBJECT_GANON2",
    "0154": "OBJECT_KA",
    "0155": "OBJECT_TS",
    "0156": "OBJECT_ZG",
    "0157": "OBJECT_GI_HOVERBOOTS",
    "0158": "OBJECT_GI_M_ARROW",
    "0159": "OBJECT_DS2",
    "015A": "OBJECT_EC",
    "015B": "OBJECT_FISH",
    "015C": "OBJECT_GI_SUTARU",
    "015D": "OBJECT_GI_GODDESS",
    "015E": "OBJECT_SSH",
    "015F": "OBJECT_BIGOKUTA",
    "0160": "OBJECT_BG",
    "0161": "OBJECT_SPOT05_OBJECTS",
    "0162": "OBJECT_SPOT12_OBJ",
    "0163": "OBJECT_BOMBIWA",
    "0164": "OBJECT_HINTNUTS",
    "0165": "OBJECT_RS",
    "0166": "OBJECT_SPOT00_BREAK",
    "0167": "OBJECT_GLA",
    "0168": "OBJECT_SHOPNUTS",
    "0169": "OBJECT_GELDB",
    "016A": "OBJECT_GR",
    "016B": "OBJECT_DOG",
    "016C": "OBJECT_JYA_IRON",
    "016D": "OBJECT_JYA_DOOR",
    "016E": "OBJECT_UNSET_16E",
    "016F": "OBJECT_SPOT11_OBJ",
    "0170": "OBJECT_KIBAKO2",
    "0171": "OBJECT_DNS",
    "0172": "OBJECT_DNK",
    "0173": "OBJECT_GI_FIRE",
    "0174": "OBJECT_GI_INSECT",
    "0175": "OBJECT_GI_BUTTERFLY",
    "0176": "OBJECT_GI_GHOST",
    "0177": "OBJECT_GI_SOUL",
    "0178": "OBJECT_BOWL",
    "0179": "OBJECT_DEMO_KEKKAI",
    "017A": "OBJECT_EFC_DOUGHNUT",
    "017B": "OBJECT_GI_DEKUPOUCH",
    "017C": "OBJECT_GANON_ANIME1",
    "017D": "OBJECT_GANON_ANIME2",
    "017E": "OBJECT_GANON_ANIME3",
    "017F": "OBJECT_GI_RUPY",
    "0180": "OBJECT_SPOT01_MATOYA",
    "0181": "OBJECT_SPOT01_MATOYAB",
    "0182": "OBJECT_MU",
    "0183": "OBJECT_WF",
    "0184": "OBJECT_SKB",
    "0185": "OBJECT_GJ",
    "0186": "OBJECT_GEFF",
    "0187": "OBJECT_HAKA_DOOR",
    "0188": "OBJECT_GS",
    "0189": "OBJECT_PS",
    "018A": "OBJECT_BWALL",
    "018B": "OBJECT_COW",
    "018C": "OBJECT_COB",
    "018D": "OBJECT_GI_SWORD_1",
    "018E": "OBJECT_DOOR_KILLER",
    "018F": "OBJECT_OUKE_HAKA",
    "0190": "OBJECT_TIMEBLOCK",
    "0191": "OBJECT_ZL4"
}

# Dictionnary containing Objects' Names
objectsNames = {
    "OBJECT_UNSET_0": "",
    "OBJECT_GAMEPLAY_KEEP": "Global Gameplay Objects",
    "OBJECT_GAMEPLAY_FIELD_KEEP": "Global Field Objects",
    "OBJECT_GAMEPLAY_DANGEON_KEEP": "Global Dungeon Objects",
    "OBJECT_UNSET_4": "",
    "OBJECT_UNSET_5": "",
    "OBJECT_HUMAN": "Aria",
    "OBJECT_OKUTA": "Octorok",
    "OBJECT_CROW": "Guay",
    "OBJECT_POH": "Poe",
    "OBJECT_DY_OBJ": "Great Fairy",
    "OBJECT_WALLMASTER": "Floormaster & Wallmaster",
    "OBJECT_DODONGO": "Dodongo",
    "OBJECT_FIREFLY": "Keese",
    "OBJECT_BOX": "Treasure Chest",
    "OBJECT_FIRE": "Dancing Flame",
    "OBJECT_UNSET_10": "",
    "OBJECT_UNSET_11": "",
    "OBJECT_BUBBLE": "Shabom",
    "OBJECT_NIW": "Cucco",
    "OBJECT_LINK_BOY": "Adult Link",
    "OBJECT_LINK_CHILD": "Child Link",
    "OBJECT_TITE": "Tektites",
    "OBJECT_REEBA": "Leever",
    "OBJECT_PEEHAT": "Peahat",
    "OBJECT_KINGDODONGO": "King Dodongo",
    "OBJECT_HORSE": "Epona",
    "OBJECT_ZF": "Lizalfos & Dinolfos",
    "OBJECT_GOMA": "Gohma",
    "OBJECT_ZL1": "Child Zelda",
    "OBJECT_GOL": "Gohma Larva",
    "OBJECT_DODOJR": "Baby Dodongo",
    "OBJECT_TORCH2": "Dark Link",
    "OBJECT_BL": "Biri",
    "OBJECT_TP": "Tailpasaran",
    "OBJECT_OA1": "Kakariko Rooftop Man",
    "OBJECT_ST": "Skulltulas",
    "OBJECT_BW": "Torch Slug",
    "OBJECT_EI": "Stingers",
    "OBJECT_HORSE_NORMAL": "Generic Horse",
    "OBJECT_OB1": "Bazaar Proprietor",
    "OBJECT_O_ANIME": "NPC Animations I",
    "OBJECT_SPOT04_OBJECTS": "Kokiri Forest Objects",
    "OBJECT_DDAN_OBJECTS": "Dodongo's Cavern Objects",
    "OBJECT_HIDAN_OBJECTS": "Fire Temple Objects",
    "OBJECT_HORSE_GANON": "Ganondorf's Horse",
    "OBJECT_OA2": "Zora [Early]",
    "OBJECT_SPOT00_OBJECTS": "Hyrule Field Objects (Child)",
    "OBJECT_MB": "Moblins",
    "OBJECT_BOMBF": "Bomb Flower",
    "OBJECT_SK2": "Stalfos",
    "OBJECT_OE1": "Mido I [Early]",
    "OBJECT_OE_ANIME": "NPC Animations II",
    "OBJECT_OE2": "Red-Haired Kokiri Girl [Early]",
    "OBJECT_YDAN_OBJECTS": "Inside the Deku Tree Objects",
    "OBJECT_GND": "Phantom Ganon",
    "OBJECT_AM": "Armos",
    "OBJECT_DEKUBABA": "Deku Babas",
    "OBJECT_UNSET_3A": "",
    "OBJECT_OA3": "Impa's Masked Head [Early]",
    "OBJECT_OA4": "Laughing Man [Early]",
    "OBJECT_OA5": "Hylian Woman in Purple Dress",
    "OBJECT_OA6": "Hylian Man in Blue Shirt & Orange Pants",
    "OBJECT_OA7": "Hylian Woman in White Shirt & Orange Pants",
    "OBJECT_JJ": "Jabu-Jabu",
    "OBJECT_OA8": "Old Hylian Man [Early]",
    "OBJECT_OA9": "Old Hylian Man's Head [Early]",
    "OBJECT_OB2": "Hylian Man in Purple Shirt & Green Pants",
    "OBJECT_OB3": "Carpenter Boss's Wife [Early]",
    "OBJECT_OB4": "Hylian Woman in Blue Shirt & White Dress",
    "OBJECT_HORSE_ZELDA": "Zelda's Horse",
    "OBJECT_OPENING_DEMO1": "Opening Cutscene Animations",
    "OBJECT_WARP1": "Warp Circle & Rupee Prism",
    "OBJECT_B_HEART": "Heart Container [Early]",
    "OBJECT_DEKUNUTS": "Mad Scrub",
    "OBJECT_OE3": "Saria [Early]",
    "OBJECT_OE4": "Red-Haired Kokiri Boy I [Early]",
    "OBJECT_MENKURI_OBJECTS": "Gerudo Training Ground Objects",
    "OBJECT_OE5": "Fado [Early]",
    "OBJECT_OE6": "Kokiri Girl in Brown Band's Head",
    "OBJECT_OE7": "Kokiri Boy in Green Cap's Head",
    "OBJECT_OE8": "Kokiri Girl in Green Band's Head",
    "OBJECT_OE9": "Kokiri Boy in Mint Cap's Head",
    "OBJECT_OE10": "Kokiri Shop Proprietor's Head [Early]",
    "OBJECT_OE11": "Kokiri Girl in Green Cap's Head",
    "OBJECT_OE12": "Fado's Head [Early]",
    "OBJECT_VALI": "Bari",
    "OBJECT_OA10": "Soldier [Early]",
    "OBJECT_OA11": "Soldier (Courtyard) [Early]",
    "OBJECT_MIZU_OBJECTS": "Water Temple Objects",
    "OBJECT_FHG": "Phantom Ganon's Horse & Objects",
    "OBJECT_OSSAN": "Shooting Gallery & Bazaar Proprietors",
    "OBJECT_MORI_HINERI1": "Forest Temple Room 13 (Twisted)",
    "OBJECT_BB": "Bubbles",
    "OBJECT_TOKI_OBJECTS": "Temple of Time Objects",
    "OBJECT_YUKABYUN": "Flying Floor Tile",
    "OBJECT_ZL2": "Adult Zelda",
    "OBJECT_MJIN": "Warp Pad Base",
    "OBJECT_MJIN_FLASH": "Light Warp Pad",
    "OBJECT_MJIN_DARK": "Shadow Warp Pad",
    "OBJECT_MJIN_FLAME": "Fire Warp Pad",
    "OBJECT_MJIN_ICE": "Water Warp Pad",
    "OBJECT_MJIN_SOUL": "Spirit Warp Pad",
    "OBJECT_MJIN_WIND": "Forest Warp Pad",
    "OBJECT_MJIN_OKA": "Ocarina Pedestal",
    "OBJECT_HAKA_OBJECTS": "Shadow Temple Objects",
    "OBJECT_SPOT06_OBJECTS": "Lake Hylia Objects",
    "OBJECT_ICE_OBJECTS": "Ice Cavern Objects",
    "OBJECT_RELAY_OBJECTS": "Dampé's Relay Race Objects",
    "OBJECT_PO_FIELD": "Big Poe & Poe Guide",
    "OBJECT_PO_COMPOSER": "Sharp & Flat",
    "OBJECT_MORI_HINERI1A": "Forest Temple Room 13 (Straight)",
    "OBJECT_MORI_HINERI2": "Forest Temple Room 14 (Straight)",
    "OBJECT_MORI_HINERI2A": "Forest Temple Room 14 (Twisted)",
    "OBJECT_MORI_OBJECTS": "Forest Temple Objects",
    "OBJECT_MORI_TEX": "Forest Temple Textures",
    "OBJECT_SPOT08_OBJ": "Zora's Fountain Objects",
    "OBJECT_WARP2": "[Blank]",
    "OBJECT_HATA": "Flagpole",
    "OBJECT_BIRD": "Brown Bird",
    "OBJECT_UNSET_78": "",
    "OBJECT_UNSET_79": "",
    "OBJECT_UNSET_7A": "",
    "OBJECT_UNSET_7B": "",
    "OBJECT_WOOD02": "Bushes & Trees",
    "OBJECT_UNSET_7D": "",
    "OBJECT_UNSET_7E": "",
    "OBJECT_UNSET_7F": "",
    "OBJECT_UNSET_80": "",
    "OBJECT_LIGHTBOX": "Rectangular Stone Blocks (Light Grey)",
    "OBJECT_PU_BOX": "Rectangular Stone Blocks (Dark Grey)",
    "OBJECT_UNSET_83": "",
    "OBJECT_UNSET_84": "",
    "OBJECT_TRAP": "Blade Trap",
    "OBJECT_VASE": "Orange Pot",
    "OBJECT_IM": "Impa",
    "OBJECT_TA": "Talon",
    "OBJECT_TK": "Dampé & Ghost",
    "OBJECT_XC": "Sheik",
    "OBJECT_VM": "Beamos",
    "OBJECT_BV": "Barinade",
    "OBJECT_HAKACH_OBJECTS": "Bottom of the Well Objects",
    "OBJECT_EFC_CRYSTAL_LIGHT": "[?]",
    "OBJECT_EFC_FIRE_BALL": "Goddesses' Flame of Creation",
    "OBJECT_EFC_FLASH": "[Blank]",
    "OBJECT_EFC_LGT_SHOWER": "Goddess Light Dome",
    "OBJECT_EFC_STAR_FIELD": "Light Beam & Rubble",
    "OBJECT_GOD_LGT": "Golden Goddesses",
    "OBJECT_LIGHT_RING": "Jagged-Edged Light Ring",
    "OBJECT_TRIFORCE_SPOT": "Triforce & Beam of Light",
    "OBJECT_BDAN_OBJECTS": "Inside Jabu-Jabu's Belly Objects",
    "OBJECT_SD": "Soldiers",
    "OBJECT_RD": "Redead & Gibdo",
    "OBJECT_PO_SISTERS": "Poe Sisters & Objects",
    "OBJECT_HEAVY_OBJECT": "Golden Gauntlets Boulder",
    "OBJECT_GNDD": "Ganondorf (Cutscenes)",
    "OBJECT_FD": "Volvagia (Flying)",
    "OBJECT_DU": "Darunia",
    "OBJECT_FW": "Flare Dancer",
    "OBJECT_MEDAL": "Medallions [Early]",
    "OBJECT_HORSE_LINK_CHILD": "Child Epona",
    "OBJECT_SPOT02_OBJECTS": "Graveyard Objects",
    "OBJECT_HAKA": "Gravestone",
    "OBJECT_RU1": "Child Ruto",
    "OBJECT_SYOKUDAI": "Torches",
    "OBJECT_FD2": "Volvagia (Whack-a-Mole)",
    "OBJECT_DH": "Dead Hand & Hands",
    "OBJECT_RL": "Rauru",
    "OBJECT_EFC_TW": "Time Block Disappearance Effect",
    "OBJECT_DEMO_TRE_LGT": "[Blank]",
    "OBJECT_GI_KEY": "Item Model - Small Key",
    "OBJECT_MIR_RAY": "Mirror Shield's Light Reflection",
    "OBJECT_BROB": "Jelly Platform",
    "OBJECT_GI_JEWEL": "Item Model - Spiritual Stones",
    "OBJECT_SPOT09_OBJ": "Gerudo Valley Objects",
    "OBJECT_SPOT18_OBJ": "Goron City Objects",
    "OBJECT_BDOOR": "Boss Doors",
    "OBJECT_SPOT17_OBJ": "Death Mountain Crater Objects",
    "OBJECT_SHOP_DUNGEN": "Shop Shelves",
    "OBJECT_NB": "Nabooru",
    "OBJECT_MO": "Morpha",
    "OBJECT_SB": "Shellblade",
    "OBJECT_GI_MELODY": "Item Model - Music Notes",
    "OBJECT_GI_HEART": "Item Model - Recovery Heart",
    "OBJECT_GI_COMPASS": "Item Model - Compass",
    "OBJECT_GI_BOSSKEY": "Item Model - Big Key",
    "OBJECT_GI_MEDAL": "Item Model - Medallions",
    "OBJECT_GI_NUTS": "Item Model - Deku Nut",
    "OBJECT_SA": "Saria",
    "OBJECT_GI_HEARTS": "Item Model - Heart Container & Piece of Heart",
    "OBJECT_GI_ARROWCASE": "Item Model - Quivers",
    "OBJECT_GI_BOMBPOUCH": "Item Model - Bomb Bags",
    "OBJECT_IN": "Ingo",
    "OBJECT_TR": "Kotake & Koume",
    "OBJECT_SPOT16_OBJ": "Death Mountain Trail Objects",
    "OBJECT_OE1S": "Mido II [Early]",
    "OBJECT_OE4S": "Red-Haired Kokiri Boy II [Early]",
    "OBJECT_OS_ANIME": "NPC Animations III",
    "OBJECT_GI_BOTTLE": "Item Model - Empty Bottle",
    "OBJECT_GI_STICK": "Item Model - Deku Stick",
    "OBJECT_GI_MAP": "Item Model - Dungeon Map & Stone of Agony",
    "OBJECT_OF1D_MAP": "Goron, Medigoron, Biggoron",
    "OBJECT_RU2": "Adult Ruto",
    "OBJECT_GI_SHIELD_1": "Item Model - Deku Shield",
    "OBJECT_DEKUJR": "Deku Tree Sprout",
    "OBJECT_GI_MAGICPOT": "Item Model - Magic Jars",
    "OBJECT_GI_BOMB_1": "Item Model - Bomb",
    "OBJECT_OF1S": "Goron [Early]",
    "OBJECT_MA2": "Adult Malon",
    "OBJECT_GI_PURSE": "Item Model - Wallets",
    "OBJECT_HNI": "Ingo's Horse & Archery Range Horse",
    "OBJECT_TW": "Twinrova",
    "OBJECT_RR": "Like Like",
    "OBJECT_BXA": "Parasitic Tentacle & Tentacle Obstruction",
    "OBJECT_ANUBICE": "Anubis & Fire Trap",
    "OBJECT_GI_GERUDO": "Item Model - Gerudo Card",
    "OBJECT_GI_ARROW": "Item Model - Arrows",
    "OBJECT_GI_BOMB_2": "Item Model - Bombchu",
    "OBJECT_GI_EGG": "Item Model - Pocket & Weird Eggs",
    "OBJECT_GI_SCALE": "Item Model - Silver & Golden Scales",
    "OBJECT_GI_SHIELD_2": "Item Model - Hylian Shield",
    "OBJECT_GI_HOOKSHOT": "Item Model - Hookshot & Longshot",
    "OBJECT_GI_OCARINA": "Item Model - Ocarina of Time",
    "OBJECT_GI_MILK": "Item Model - Lon Lon Milk",
    "OBJECT_MA1": "Child Malon",
    "OBJECT_GANON": "Ganondorf (Boss)",
    "OBJECT_SST": "Bongo Bongo",
    "OBJECT_NY_UNUSED": "Spike Trap [Duplicate]",
    "OBJECT_UNSET_E4": "",
    "OBJECT_NY": "Spike Trap",
    "OBJECT_FR": "Frog",
    "OBJECT_GI_PACHINKO": "Item Model - Fairy Slingshot",
    "OBJECT_GI_BOOMERANG": "Item Model - Boomerang",
    "OBJECT_GI_BOW": "Item Model - Fairy Bow",
    "OBJECT_GI_GLASSES": "Item Model - Lens of Truth",
    "OBJECT_GI_LIQUID": "Item Model - Potions",
    "OBJECT_ANI": "Kakariko Rooftop Man",
    "OBJECT_DEMO_6K": "Chamber of the Sages Cutscene Objects",
    "OBJECT_GI_SHIELD_3": "Item Model - Mirror Shield",
    "OBJECT_GI_LETTER": "Item Model - Zelda's Letter",
    "OBJECT_SPOT15_OBJ": "Hyrule Castle Objects",
    "OBJECT_JYA_OBJ": "Spirit Temple Objects",
    "OBJECT_GI_CLOTHES": "Item Model - Tunics",
    "OBJECT_GI_BEAN": "Item Model - Magic Bean",
    "OBJECT_GI_FISH": "Item Model - Fish",
    "OBJECT_GI_SAW": "Item Model - Poacher's Saw",
    "OBJECT_GI_HAMMER": "Item Model - Megaton Hammer",
    "OBJECT_GI_GRASS": "Item Model - Reed Whistle",
    "OBJECT_GI_LONGSWORD": "Item Model - Giant's Knife & Biggoron's Sword",
    "OBJECT_SPOT01_OBJECTS": "Kakariko Village Objects (Shared)",
    "OBJECT_MD_UNUSED": "Mido [Duplicate]",
    "OBJECT_MD": "Mido",
    "OBJECT_KM1": "Red-Haired Kokiri Boy",
    "OBJECT_KW1": "Red-Haired Kokiri Girl",
    "OBJECT_ZO": "Zora",
    "OBJECT_KZ": "King Zora",
    "OBJECT_UMAJUMP": "Horse-Jumping Fence",
    "OBJECT_MASTERKOKIRI": "Kokiri Shop Proprietor Animations",
    "OBJECT_MASTERKOKIRIHEAD": "Kokiri Shop Proprietor's Head",
    "OBJECT_MASTERGOLON": "Goron Shop Proprietor Animations",
    "OBJECT_MASTERZOORA": "Zora Shop Proprietor Animations",
    "OBJECT_AOB": "Dog Lady",
    "OBJECT_IK": "Iron Knuckle",
    "OBJECT_AHG": "Hylian Men I",
    "OBJECT_CNE": "Young Hylian Women",
    "OBJECT_GI_NIWATORI": "Item Model - Cuccos",
    "OBJECT_SKJ": "Skull Kid",
    "OBJECT_GI_BOTTLE_LETTER": "Item Model - Ruto's Letter",
    "OBJECT_BJI": "Old Hylian Men",
    "OBJECT_BBA": "Old Hylian Woman",
    "OBJECT_GI_OCARINA_0": "Item Model - Fairy Ocarina",
    "OBJECT_DS": "Potion Shop Granny",
    "OBJECT_ANE": "Cucco Lady",
    "OBJECT_BOJ": "Hylian Men II",
    "OBJECT_SPOT03_OBJECT": "Zora's River Objects",
    "OBJECT_SPOT07_OBJECT": "Zora's Domain Objects",
    "OBJECT_FZ": "Freezard",
    "OBJECT_BOB": "Carpenter Boss's Wife",
    "OBJECT_GE1": "Gerudo in White",
    "OBJECT_YABUSAME_POINT": "Minigame Points",
    "OBJECT_GI_BOOTS_2": "Item Model - Iron Boots",
    "OBJECT_GI_SEED": "Item Model - Deku Seeds",
    "OBJECT_GND_MAGIC": "Ganondorf's Magic Blast",
    "OBJECT_D_ELEVATOR": "Stone Elevator Pillar",
    "OBJECT_D_HSBLOCK": "Hookshot Pillar & Wall Target",
    "OBJECT_D_LIFT": "Stone Moving Deku Tree Platform",
    "OBJECT_MAMENOKI": "Magic Bean Objects",
    "OBJECT_GOROIWA": "Rolling Boulder",
    "OBJECT_UNSET_120": "",
    "OBJECT_TORYO": "Carpenter Boss",
    "OBJECT_DAIKU": "Carpenters",
    "OBJECT_UNSET_123": "",
    "OBJECT_NWC": "Cucco Chick",
    "OBJECT_BLKOBJ": "Dark Link's Illusion Room",
    "OBJECT_GM": "Medigoron Animations",
    "OBJECT_MS": "Magic Bean Seller",
    "OBJECT_HS": "Carpenter Boss's Son",
    "OBJECT_INGATE": "Ingo's Ranch Gate",
    "OBJECT_LIGHTSWITCH": "Sun Switch",
    "OBJECT_KUSA": "Grass",
    "OBJECT_TSUBO": "Pot",
    "OBJECT_GI_GLOVES": "Item Model - Silver & Golden Gauntlets",
    "OBJECT_GI_COIN": "Item Model - N Coins",
    "OBJECT_KANBAN": "Square Signpost",
    "OBJECT_GJYO_OBJECTS": "Ganon's Castle Exterior Objects",
    "OBJECT_OWL": "Kaepora Gaebora",
    "OBJECT_MK": "Lake Scientist",
    "OBJECT_FU": "Windmill Man",
    "OBJECT_GI_KI_TAN_MASK": "Item Model - Keaton Mask",
    "OBJECT_GI_REDEAD_MASK": "Item Model - Redead Mask",
    "OBJECT_GI_SKJ_MASK": "Item Model - Spooky Mask",
    "OBJECT_GI_RABIT_MASK": "Item Model - Bunny Hood",
    "OBJECT_GI_TRUTH_MASK": "Item Model - Mask of Truth",
    "OBJECT_GANON_OBJECTS": "Ganon's Tower Objects",
    "OBJECT_SIOFUKI": "Water Spout (Small)",
    "OBJECT_STREAM": "Water Spout (Large)",
    "OBJECT_MM": "Running Man",
    "OBJECT_FA": "Fado",
    "OBJECT_OS": "Happy Mask Salesman",
    "OBJECT_GI_EYE_LOTION": "Item Model - Eyedrops",
    "OBJECT_GI_POWDER": "Item Model - Odd Potion",
    "OBJECT_GI_MUSHROOM": "Item Model - Odd Mushroom",
    "OBJECT_GI_TICKETSTONE": "Item Model - Claim Check",
    "OBJECT_GI_BROKENSWORD": "Item Model - Broken Goron's Sword & Giant's Knife",
    "OBJECT_JS": "Carpet Merchant",
    "OBJECT_CS": "Graveyard Boy",
    "OBJECT_GI_PRESCRIPTION": "Item Model - Prescription",
    "OBJECT_GI_BRACELET": "Item Model - Goron Bracelet",
    "OBJECT_GI_SOLDOUT": "Item Model - SOLD OUT",
    "OBJECT_GI_FROG": "Item Model - Eyeball Frog",
    "OBJECT_MAG": "Title Logo",
    "OBJECT_DOOR_GERUDO": "Thieves' Hideout Cell Door",
    "OBJECT_GT": "Ganon's Tower Exterior (Collapsing) Objects",
    "OBJECT_EFC_ERUPC": "Death Mountain Eruption Effects",
    "OBJECT_ZL2_ANIME1": "Adult Zelda Animations I",
    "OBJECT_ZL2_ANIME2": "Adult Zelda Animations II",
    "OBJECT_GI_GOLONMASK": "Item Model - Goron Mask",
    "OBJECT_GI_ZORAMASK": "Item Model - Zora Mask",
    "OBJECT_GI_GERUDOMASK": "Item Model - Gerudo Mask",
    "OBJECT_GANON2": "Ganon",
    "OBJECT_KA": "Pierre & Bonooru",
    "OBJECT_TS": "Treasure Chest Shop Proprietor",
    "OBJECT_ZG": "Ganon's Tower Door Bars",
    "OBJECT_GI_HOVERBOOTS": "Item Model - Hover Boots",
    "OBJECT_GI_M_ARROW": "Item Model - Magic Arrows",
    "OBJECT_DS2": "Potion Shop Proprietor",
    "OBJECT_EC": "Ending Cutscene Animations",
    "OBJECT_FISH": "Fishing Pond Objects",
    "OBJECT_GI_SUTARU": "Item Model - Gold Skulltula Token",
    "OBJECT_GI_GODDESS": "Item Model - Goddess Spells",
    "OBJECT_SSH": "Skulltula House Residents",
    "OBJECT_BIGOKUTA": "Big Octo",
    "OBJECT_BG": "Bombchu Bowling Employee",
    "OBJECT_SPOT05_OBJECTS": "Sacred Forest Meadow Objects",
    "OBJECT_SPOT12_OBJ": "Gerudo's Fortress Objects",
    "OBJECT_BOMBIWA": "Bombable Boulder",
    "OBJECT_HINTNUTS": "Hint-Giving Deku Scrub",
    "OBJECT_RS": "Bombchu Shop Proprietor",
    "OBJECT_SPOT00_BREAK": "Hyrule Field Objects (Adult)",
    "OBJECT_GLA": "Gerudo in Purple",
    "OBJECT_SHOPNUTS": "Business Scrub",
    "OBJECT_GELDB": "Gerudo Fighter & Second-in-Command",
    "OBJECT_GR": "Cucco-Chasing Girl",
    "OBJECT_DOG": "Dog",
    "OBJECT_JYA_IRON": "Destructable Iron Knuckle Objects",
    "OBJECT_JYA_DOOR": "Spirit Temple Door & Iron Bars",
    "OBJECT_UNSET_16E": "",
    "OBJECT_SPOT11_OBJ": "Desert Colossus Objects",
    "OBJECT_KIBAKO2": "Large Wooden Crate",
    "OBJECT_DNS": "Forest Stage Judge",
    "OBJECT_DNK": "Forest Stage Patron",
    "OBJECT_GI_FIRE": "Item Model - Blue Fire",
    "OBJECT_GI_INSECT": "Item Model - Bug",
    "OBJECT_GI_BUTTERFLY": "Item Model - Butterfly",
    "OBJECT_GI_GHOST": "Item Model - Poe Soul",
    "OBJECT_GI_SOUL": "Item Model - Fairy's Spirit",
    "OBJECT_BOWL": "Bombchu Bowling Alley Barriers",
    "OBJECT_DEMO_KEKKAI": "Inside Ganon's Castle Objects",
    "OBJECT_EFC_DOUGHNUT": "Death Mountain Cloud Rings",
    "OBJECT_GI_DEKUPOUCH": "Item Model - Bullet Bags",
    "OBJECT_GANON_ANIME1": "Ganondorf Animations I",
    "OBJECT_GANON_ANIME2": "Ganondorf Animations II",
    "OBJECT_GANON_ANIME3": "Ganondorf Animations III",
    "OBJECT_GI_RUPY": "Item Model - Rupees",
    "OBJECT_SPOT01_MATOYA": "Kakariko Village Objects (Adult)",
    "OBJECT_SPOT01_MATOYAB": "Kakariko Village Objects (Child)",
    "OBJECT_MU": "Honey & Darling, Haggling Townspeople",
    "OBJECT_WF": "Wolfos",
    "OBJECT_SKB": "Stalchild",
    "OBJECT_GJ": "Ganon's Lair Destructable Rubble",
    "OBJECT_GEFF": "Ganon's Lair Destructable Rubble Fragment",
    "OBJECT_HAKA_DOOR": "Shadow Temple Door & Shutter",
    "OBJECT_GS": "Gossip Stone",
    "OBJECT_PS": "Poe Collector",
    "OBJECT_BWALL": "Dodongo's Cavern Bombable Wall",
    "OBJECT_COW": "Cow",
    "OBJECT_COB": "Fat Woman in Blue & Yellow Vest",
    "OBJECT_GI_SWORD_1": "Item Model - Kokiri Sword",
    "OBJECT_DOOR_KILLER": "Door Mimic",
    "OBJECT_OUKE_HAKA": "Royal Family's Tomb Door",
    "OBJECT_TIMEBLOCK": "Time Block",
    "OBJECT_ZL4": "Child Zelda"
}

# Dictionnary containing every actor categories
categories = {
    "0": "ACTORCAT_SWITCH",
    "1": "ACTORCAT_BG",
    "2": "ACTORCAT_PLAYER",
    "3": "ACTORCAT_EXPLOSIVE",
    "4": "ACTORCAT_NPC",
    "5": "ACTORCAT_ENNEMY",
    "6": "ACTORCAT_PROP",
    "7": "ACTORCAT_ITEMACTION",
    "8": "ACTORCAT_MISC",
    "9": "ACTORCAT_BOSS",
    "10": "ACTORCAT_DOOR",
    "11": "ACTORCAT_CHEST"
}

ootEnWonderItemDrop = [
	("Deku Nuts", "0x00"),
	("Heart Piece", "0x01"),
	("Large Magic Jar", "0x02"),
	("Small Magic Jar", "0x03"),
	("Recovery Heart", "0x04"),
	("Arrows (5)", "0x05"),
	("Arrows (10)", "0x06"),
	("Arrows (30)", "0x07"),
	("Green Rupee", "0x08"),
	("Blue Rupee", "0x09"),
	("Red Rupee", "0x0A"),
	("Flex Drop", "0x0B"),
	("Random Drop", "0x0C")
]

ootEnItem00Drop = [
	("Green Rupee", "0x00"),
	("Blue Rupee", "0x01"),
	("Red Rupee", "0x02"),
	("Recovery Heart", "0x03"),
	("Bombs (5)", "0x04"),
	("Arrows (1)", "0x05"),
	("Heart Piece", "0x06"),
	("Heart Container", "0x07"),
	("Arrows (5)", "0x08"),
	("Arrows (10)", "0x09"),
	("Arrows (30)", "0x0A"),
	("Deku Nuts", "0x0C"),
	("Deku Sticks", "0x0D"),
	("Large Magic Jar", "0x0E"),
	("Small Magic Jar", "0x0F"),
	("Deku Seeds", "0x10"),
	("Small Key", "0x11"),
	("Flexible Drop", "0x12"),
	("Orange Rupee (200)", "0x13"),
	("Purple Rupee (50)", "0x14"),
	("Deku Shield", "0x15"),
	("Hylian Shield", "0x16"),
	("Zora Tunic", "0x17"),
	("Goron Tunic", "0x18")
]

ootEnBoxContent = [
	("Recovery Heart", "0x48"),
	("Green Rupee", "0x4C"),
	("Blue Rupee", "0x4D"),
	("Blue rupee", "0x3C"),
	("Red Rupee", "0x4E"),
	("Purple Rupee (50)", "0x55"),
	("Huge/Yellow Rupee (200)", "0x56"),
	("Bombs (1)", "0x65"),
	("Bombs (5)", "0x01"),
	("Bombs (10)", "0x66"),
	("Bombs (20)", "0x67"),
	("Bombs (30)", "0x68"),
	("Arrows (5)", "0x49"),
	("Arrows (10)", "0x4A"),
	("Arrows (30)", "0x4B"),
	("Deku Stick (1)", "0x07"),
	("Deku Stick", "0x61"),
	("Deku Stick", "0x62"),
	("Deku Nuts", "0x02"),
	("Deku Nuts", "0x63"),
	("Deku Nuts", "0x64"),
	("Bombchus (5)", "0x6A"),
	("Bombchus (10)", "0x03"),
	("Bombchus (20)", "0x6B"),
	("Deku Seeds (30)", "0x69"),
	("Small Magic Jar (?)", "0x43"),
	("Large Magic Jar (?)", "0x44"),
	("Piece of Heart", "0x3E"),
	("Deku Shield", "0x29"),
	("Hylian Shield", "0x2A"),
	("Mirror Shield", "0x2B"),
	("Goron Tunic", "0x2C"),
	("Zora Tunic", "0x2D"),
	("Iron Boots", "0x2E"),
	("Hover Boots", "0x2F"),
	("Kokiri’s Sword", "0x27"),
	("Giant’s Knife", "0x28"),
	("Biggoron’s Sword", "0x57"),
	("Goron Bracelet", "0x54"),
	("Silver Gauntlets", "0x35"),
	("Golden Gauntlets", "0x36"),
	("Silver Scale", "0x37"),
	("Golden Scale", "0x38"),
	("Fairy Bow", "0x04"),
	("Fairy Slingshot", "0x05"),
	("Boomerang", "0x06"),
	("Hookshot", "0x08"),
	("Longshot", "0x09"),
	("Lens of Truth", "0x0A"),
	("Fairy Ocarina", "0x3B"),
	("Ocarina of Time", "0x0C"),
	("Megaton Hammer", "0x0D"),
	("Magic Bean", "0x16"),
	("Fire Arrow", "0x58"),
	("Ice Arrow", "0x59"),
	("Light Arrow", "0x5A"),
	("Din’s Fire", "0x5C"),
	("Farore’s Wind", "0x5D"),
	("Nayru’s Love", "0x5E"),
	("Stone of Agony", "0x39"),
	("Gerudo Membership Card", "0x3A"),
	("Gold Skulltula Token", "0x5B"),
	("Empty Bottle", "0x0F"),
	("Red Potion", "0x10"),
	("Green Potion", "0x11"),
	("Blue Potion", "0x12"),
	("Bottled Fairy", "0x13"),
	("Lon Lon Milk", "0x14"),
	("Ruto's Letter", "0x15"),
	("Bottled Fish", "0x6C"),
	("Bottled Bug", "0x6D"),
	("Blue Fire", "0x6E"),
	("Bottled Poe", "0x6F"),
	("Bottled Big Poe", "0x70"),
	("Lon Lon Milk", "0x50"),
	("Weird Egg", "0x47"),
	("Chicken", "0x19"),
	("Zelda’s Letter", "0x0B"),
	("Keaton Mask", "0x1A"),
	("Skull Mask", "0x17"),
	("Spooky Mask", "0x18"),
	("Bunny Hood", "0x1B"),
	("Mask of Truth", "0x1C"),
	("Goron Mask", "0x51"),
	("Zora Mask", "0x52"),
	("Gerudo Mask", "0x53"),
	("Pocket Egg", "0x1D"),
	("Pocket Cucco", "0x1E"),
	("Cojiro", "0x0E"),
	("Odd Mushroom", "0x1F"),
	("Odd Potion", "0x20"),
	("Poacher’s Saw", "0x21"),
	("Broken Goron’s Sword", "0x22"),
	("Prescription", "0x23"),
	("Eyeball Frog", "0x24"),
	("World’s Finest Eye Drops", "0x25"),
	("Claim Check", "0x26"),
	("Big Quiver", "0x30"),
	("Biggest Quiver", "0x31"),
	("Bomb Bag (20)", "0x32"),
	("Big Bomb Bag (30)", "0x33"),
	("Biggest Bomb Bag (40)", "0x34"),
	("Adult Wallet", "0x45"),
	("Giant Wallet", "0x46"),
	("Deku Stick Upgrade (20)", "0x77"),
	("Deku Stick Upgrade (30)", "0x78"),
	("Deku Nut Upgrade (30)", "0x79"),
	("Deku Nut Upgrade (40)", "0x7A"),
	("Deku Seeds Bag (40)", "0x5F"),
	("Deku Seeds Bag (40)", "0x60"),
	("Deku Seeds Bag (50)", "0x7B"),
	("Compass", "0x40"),
	("Map", "0x41"),
	("Small Key", "0x42"),
	("Boss Key", "0x3F"),
	("Heart Container", "0x4F"),
	("Heart Container", "0x3D"),
	("Door Key (Treasure Box Shop)", "0x71"),
	("Loser Green Rupee (Treasure Box Shop)", "0x72"),
	("Loser Blue Rupee (Treasure Box Shop)", "0x73"),
	("Loser Red Rupee (Treasure Box Shop)", "0x74"),
	("Winner Purple Rupee (Treasure Box Shop)", "0x75"),
	("Winner Piece of Heart (Treasure Box Shop)", "0x76"),
	("Ice Trap", "0x7C")
]